default:
  version: 1.2.0
  debug: true
  encoder_param:
    epochs: 10
    batch_size: 32
    activation: relu
  splits: 4
  random_seed: 2023

layers:
  - []
  # - [20, 10, 5]
  # - [20, 15, 10, 5]
  # - [20, 15, 10]

models: [lr] # lr, lgb, svm, rf, mp
datasets:
  - name: kdd99 
    ae_used_data: normal # normal, all, u2r
    dropped: true # dropped: true, false 
    use_full: false
  # - name: kdd99
  #   ae_used_data: u2r
  #   dropped: true
  #   use_full: false
  - name: creditcardfraud
    ae_used_data: normal
  
  # imbalance: ['ecoli', 'optical_digits', 'satimage', 'pen_digits', 'abalone', 'sick_euthyroid', 'spectrometer', 'car_eval_34', 'isolet', 'us_crime', 'yeast_ml8', 'scene', 'libras_move', 'thyroid_sick', 'coil_2000', 'arrhythmia', 'solar_flare_m0', 'oil', 'car_eval_4', 'wine_quality', 'letter_img', 'yeast_me2', 'webpage', 'ozone_level', 'mammography', 'protein_homo', 'abalone_19']
  - name: imbalance
    ae_used_data: all
    dataset_name: 

    