[default]
random_seed = 2018
tf_seed = 42
np_seed = 42
dataset_path = "/Users/satun/DataspellProjects/ml/handson-unsupervised-learning/datasets/credit_card_data/credit_card.csv"
drop_x = ['Class', 'Time']
label_y = 'Class'

# 教師あり学習
[supervised]
    [supervised.k_fold]
    n_splits = 5
    shuffle = true
    random_state = 2018
    [supervised.lgb]
    task = 'train'
#    application = 'binary'
    num_class = 1
    boosting = 'gbdt'
    objective = 'binary'
    metric = 'binary_logloss'
    metric_freq = 50
    is_training_metric = false
    max_depth = 4
    num_leaves = 31
    learning_rate = 0.01
    feature_fraction = 1.0
    bagging_fraction = 1.0
    bagging_freq = 0
    bagging_seed = 2018
    num_iterations = 200
    # これを指定しないと`No further splits with positive gain, best gain: -inf`というWarningが表示される
    verbose = -1
    num_threads = 16
    [supervised.test_split]
    test_size = 0.33
    random_state = 2018
    # + stratify = data_y


# 教師なし学習
[unsupervised]
    over_sample_multiplier = 100
    [unsupervised.compile]
    optimizer = 'adam'
    loss = 'mean_squared_error'
    metrics = ['accuracy']
    [unsupervised.fit]
    epochs = 5
    batch_size = 32
    shuffle = true
    validation_split = 0.20
    verbose = 1

# 半教師あり学習
[semi_supervised]